config/routes.rb
Rails.application.routes.draw do
    get 'sessions/new'

    get 'users/new'

    get '', to: 'static_pages#index'
    get 'dashboard', to: 'static_pages#dashboard'
  
    get "log_out" => "sessions#destroy", :as => "log_out"
    get "log_in" => "sessions#new", :as => "log_in"
    get "sign_up" => "users#new", :as => "sign_up"
    root :to => "users#new"
    resources :users
    resources :sessions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/static_pages/dashboard.html.erb
<!--css--><%= stylesheet_link_tag 'reset', "static_pages" %>
<!--js--><%= javascript_include_tag "static_pages" %>
<html id="login_head">
<head>
<h1>test</h1>
</head>
<body>
<ul class="nice">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
</ul>
</body>
</html>

app/views/static_pages/index.html.erb
<!--css--><%= stylesheet_link_tag "static_pages" %>
<!--js--><%= javascript_include_tag "static_pages" %>
<html id="many">
<header>
    <h1 id="oh">coobroom alpha^4</h1>
</header>
<body>
    
<!--<hr id="meme1">-->
<a href="dashboard" id="any">Press to continue</a>
<!--<hr id="meme2" class="right">-->

</body>
</html>